namespace SlimeRepublics;

// ------------------------------------------------------------------ primitives

struct Vec2 {
  x: int;
  y: int;
}

enum Direction : byte { Up, Down, Left, Right }

// ---------------------------------------------------------------------- world

table Slime {
  id: uint;
  position: Vec2;
}

table WorldState {
  slimes: [ Slime ];
}

// --------------------------------------------------------------------- events

table MoveEvent {
  direction: Direction;
}

table PingEvent {
  origin_time: double;
}

table PongEvent {
  origin_time: double;
}

// ------------------------------------------------------------------- envelopes

union ClientEvent { MoveEvent, PingEvent, PongEvent }

table ClientInput {
  events: [ ClientEvent ];
}

union ServerEvent { WorldState, PingEvent, PongEvent }

table ServerMessage {
  events: [ ServerEvent ];
}

file_identifier "SLIM";
root_type ServerMessage;
