namespace SlimeRepublics;

// ------------------------------------------------------------------ primitives

struct Vec2 {
  x: int;
  y: int;
}

enum Direction : byte { None, Up, Down, Left, Right }

// ---------------------------------------------------------------------- world

table Slime {
  id: uint;
  position: Vec2;
  heading: Direction;
}

table WorldState {
  slimes: [ Slime ];
}

// --------------------------------------------------------------------- events

table MoveEvent {
  direction: Direction;
}

table PingEvent {
  origin_time: double;
}

table PongEvent {
  origin_time: double;
}

table InteractEvent {

}

// ------------------------------------------------------------------- envelopes

union ClientEvent { PingEvent, PongEvent, MoveEvent, InteractEvent }

table ClientInput {
  events: [ ClientEvent ] (required);
}

union ServerEvent { WorldState, PingEvent, PongEvent }

table ServerMessage {
  events: [ ServerEvent ] (required);
}

file_identifier "SLIM";
root_type ServerMessage;
