#!/usr/bin/env bash
# Regenerates the TypeScript FlatBuffers client from src/schema/*.fbs.
#
# The C++ side is NOT generated here — src/backend-cpp generates it at build
# time with vcpkg's flatc, so its version matches the C++ headers by
# construction. This script covers src/frontend only.
#
# flatc must match the `flatbuffers` npm package pinned in
# src/frontend/package.json — npm's newest is 25.9.23, while vcpkg's C++ port
# is ahead of it. Do NOT use the backend's vcpkg flatc here: the two sides are
# generated by different flatc versions on purpose, because each must match its
# own runtime. tools/install-cpp-deps.sh installs this one to ~/.local/bin.
set -euo pipefail

FLATC_VERSION=25.9.23

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
schema_dir="$repo_root/src/schema"
ts_out="$repo_root/src/frontend/src/generated"

flatc="$(command -v flatc || true)"
if [[ -z "$flatc" ]]; then
  echo "no flatc on PATH — run tools/install-cpp-deps.sh" >&2
  exit 1
fi

have="$("$flatc" --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
if [[ "$have" != "$FLATC_VERSION" ]]; then
  echo "flatc $FLATC_VERSION required, found $have — see src/schema/README.md" >&2
  exit 1
fi

rm -rf "$ts_out"
mkdir -p "$ts_out"

"$flatc" --ts --gen-all -o "$ts_out" "$schema_dir"/*.fbs

# A union with no members makes flatc emit empty type positions — `(obj:) => |null`
# — which is not parseable TypeScript. @ts-nocheck does not save it: that suppresses
# type errors, not syntax errors, so tsc, Vite and Vitest all fail to read the file.
# Fill the holes in; with the union empty these helpers can only ever return null,
# so the type they carry is immaterial. Delete this once EventData has members again.
while IFS= read -r -d '' f; do
  perl -0pi -e 's/obj:\)/obj: unknown)/g; s/=> \|null/=> unknown|null/g; s/\): \|null/): unknown|null/g' "$f"
done < <(find "$ts_out" -name '*.ts' -print0)

# flatc emits unused union helpers and type params, which trip the project's
# noUnusedLocals/noUnusedParameters. Generated code is not ours to fix, so opt
# these files out of checking; their exported types still flow to callers.
while IFS= read -r -d '' f; do
  printf '// @ts-nocheck\n%s' "$(cat "$f")" > "$f"
done < <(find "$ts_out" -name '*.ts' -print0)

echo "generated -> $ts_out"
